const baseImageUrl= 'https://gateway.pinata.cloud/ipfs/QmQY5pdEEb6Z5RcZPs1KiNn27Pog2LAf4G9hDtrBjJjg1v/';

export const imageMapping = {
  'Baby Elephant': baseImageUrl + 'Elephant/Baby%20Elephant.jpg',
  'Baby Elk': baseImageUrl + 'ELK/Baby%20Elk.jpg',
  'Baby Gorilla': baseImageUrl + 'Gorilla/Baby%20Gorilla.jpg',
  'Baby Orca': baseImageUrl + 'Orca/Baby%20Orca.jpg',
  'Baby Shark': baseImageUrl + 'Shark/Baby%20Shark.jpg',
  Banda: baseImageUrl + 'Bear/Banda.jpg',
  Bear: baseImageUrl + 'Bear/Bear.jpg',
  Bearblob: baseImageUrl + 'Bear/Bearblob.jpg',
  Bearca: baseImageUrl + 'Bear/Bearca.jpg',
  'Bear Cub': baseImageUrl + 'Bear/Bear%20Cub.jpg',
  Bearilla: baseImageUrl + 'Bear/Bearilla.jpg',
  Bearling: baseImageUrl + 'Bear/Bearling.jpg',
  Bearlion: baseImageUrl + 'Bear/Bearlion.jpg',
  Bearpug: baseImageUrl + 'Bear/Bearpug.jpg',
  Bearrat: baseImageUrl + 'Bear/Bearrat.jpg',
  Bearshark: baseImageUrl + 'Bear/Bearshark.jpg',
  Beartle: baseImageUrl + 'Bear/Beartle.jpg',
  Beartten: baseImageUrl + 'Bear/Beartten.jpg',
  Beartterfly: baseImageUrl + 'Bear/Beartterfly.jpg',
  Belephant: baseImageUrl + 'Bear/Belephant.jpg',
  Belk: baseImageUrl + 'Bear/Belk.jpg',
  Benguin: baseImageUrl + 'Bear/Benguin.jpg',
  Blobfish: baseImageUrl + 'Blobfish/Blobfish.jpg',
  Butterbear: baseImageUrl + 'Butterfly/Butterbear.jpg',
  Butterblob: baseImageUrl + 'Butterfly/Butterblob.jpg',
  Butterflanda: baseImageUrl + 'Butterfly/Butterflanda.jpg',
  Butterflelk: baseImageUrl + 'Butterfly/Butterflelk.jpg',
  Butterflenguin: baseImageUrl + 'Butterfly/Butterflenguin.jpg',
  Butterfling: baseImageUrl + 'Butterfly/Butterfling.jpg',
  Butterflion: baseImageUrl + 'Butterfly/Butterflion.jpg',
  Butterflitten: baseImageUrl + 'Butterfly/Butterflitten.jpg',
  Butterfly: baseImageUrl + 'Butterfly/Butterfly.jpg',
  Butterla: baseImageUrl + 'Butterfly/Butterla.jpg',
  Butterphant: baseImageUrl + 'Butterfly/Butterphant.jpg',
  Butterpug: baseImageUrl + 'Butterfly/Butterpug.jpg',
  Butterrat: baseImageUrl + 'Butterfly/Butterrat.jpg',
  Buttershark: baseImageUrl + 'Butterfly/Buttershark.jpg',
  Buttorca: baseImageUrl + 'Butterfly/Buttorca.jpg',
  Butturtle: baseImageUrl + 'Butterfly/Butturtle.jpg',
  Caterpillar: baseImageUrl + 'Butterfly/Caterpillar.jpg',
  Dorca: baseImageUrl + 'Duckling/Dorca.jpg',
  Duckbear: baseImageUrl + 'Duckling/Duckbear.jpg',
  Duckblob: baseImageUrl + 'Duckling/Duckblob.jpg',
  Duckda: baseImageUrl + 'Duckling/Duckda.jpg',
  Duckelk: baseImageUrl + 'Duckling/Duckelk.jpg',
  Duckerfly: baseImageUrl + 'Duckling/Duckerfly.jpg',
  Duckitten: baseImageUrl + 'Duckling/Duckitten.jpg',
  Ducklephant: baseImageUrl + 'Duckling/Ducklephant.jpg',
  Duckling: baseImageUrl + 'Duckling/Duckling.jpg',
  Ducklinguin: baseImageUrl + 'Duckling/Ducklinguin.jpg',
  Ducklion: baseImageUrl + 'Duckling/Ducklion.jpg',
  Duckorilla: baseImageUrl + 'Duckling/Duckorilla.jpg',
  DuckPug: baseImageUrl + 'Duckling/DuckPug.jpg',
  Duckrat: baseImageUrl + 'Duckling/Duckrat.jpg',
  Duckshark: baseImageUrl + 'Duckling/Duckshark.jpg',
  Durtle: baseImageUrl + 'Duckling/Durtle.jpg',
  Elebear: baseImageUrl + 'Elephant/Elebear.jpg',
  Eleblob: baseImageUrl + 'Elephant/Eleblob.jpg',
  Elepanda: baseImageUrl + 'Elephant/Elepanda.jpg',
  Elepenguin: baseImageUrl + 'Elephant/Elepenguin.jpg',
  Elephant: baseImageUrl + 'Elephant/Elephant.jpg',
  Elephantilla: baseImageUrl + 'Elephant/Elephantilla.jpg',
  Elephantterfly: baseImageUrl + 'Elephant/Elephantterfly.jpg',
  Elephanturtle: baseImageUrl + 'Elephant/Elephanturtle.jpg',
  Elephelk: baseImageUrl + 'Elephant/Elephelk.jpg',
  Elephitten: baseImageUrl + 'Elephant/Elephitten.jpg',
  Elephling: baseImageUrl + 'Elephant/Elephling.jpg',
  Elephlion: baseImageUrl + 'Elephant/Elephlion.jpg',
  Elephorca: baseImageUrl + 'Elephant/Elephorca.jpg',
  Elephrat: baseImageUrl + 'Elephant/Elephrat.jpg',
  Elepug: baseImageUrl + 'Elephant/Elepug.jpg',
  Eleshark: baseImageUrl + 'Elephant/Eleshark.jpg',
  Elk: baseImageUrl + 'ELK/Elk.jpg',
  Elka: baseImageUrl + 'ELK/Elka.jpg',
  Elkanda: baseImageUrl + 'ELK/Elkanda.jpg',
  Elkbear: baseImageUrl + 'ELK/Elkbear.jpg',
  Elkenguin: baseImageUrl + 'ELK/Elkenguin.jpg',
  Elkephant: baseImageUrl + 'ELK/Elkephant.jpg',
  Elkerfly: baseImageUrl + 'ELK/Elkerfly.jpg',
  Elkfish: baseImageUrl + 'ELK/Elkfish.jpg',
  Elkion: baseImageUrl + 'ELK/Elkion.jpg',
  Elkitten: baseImageUrl + 'ELK/Elkitten.jpg',
  Elkling: baseImageUrl + 'ELK/Elkling.jpg',
  Elkorilla: baseImageUrl + 'ELK/Elkorilla.jpg',
  Elkpug: baseImageUrl + 'ELK/Elkpug.jpg',
  'Elk Rat': baseImageUrl + 'ELK/Elk%20Rat.jpg',
  Elkshark: baseImageUrl + 'ELK/Elkshark.jpg',
  Elkurtle: baseImageUrl + 'ELK/Elkurtle.jpg',
  'Gen 1 Egg': baseImageUrl + 'Duckling/Gen%201%20Egg.jpg',
  Goranda: baseImageUrl + 'Gorilla/Goranda.jpg',
  Gorca: baseImageUrl + 'Gorilla/Gorca.jpg',
  Gorilla: baseImageUrl + 'Gorilla/Gorilla.jpg',
  Gorillabear: baseImageUrl + 'Gorilla/Gorillabear.jpg',
  Gorillablob: baseImageUrl + 'Gorilla/Gorillablob.jpg',
  Gorillafly: baseImageUrl + 'Gorilla/Gorillafly.jpg',
  Gorillaguin: baseImageUrl + 'Gorilla/Gorillaguin.jpg',
  Gorillaphant: baseImageUrl + 'Gorilla/Gorillaphant.jpg',
  'Gorilla Rat': baseImageUrl + 'Gorilla/Gorilla%20Rat.jpg',
  Gorillark: baseImageUrl + 'Gorilla/Gorillark.jpg',
  Gorillelk: baseImageUrl + 'Gorilla/Gorillelk.jpg',
  Gorilling: baseImageUrl + 'Gorilla/Gorilling.jpg',
  Gorillion: baseImageUrl + 'Gorilla/Gorillion.jpg',
  Gorkitten: baseImageUrl + 'Gorilla/Gorkitten.jpg',
  Gorturtle: baseImageUrl + 'Gorilla/Gorturtle.jpg',
  Gug: baseImageUrl + 'Gorilla/Gug.jpg',
  Kittelk: baseImageUrl + 'Kittens/Kittelk.jpg',
  Kitten: baseImageUrl + 'Kittens/Kittens.jpg',
  Kitterfly: baseImageUrl + 'Kittens/Kitterfly.jpg',
  Kittorca: baseImageUrl + 'Kittens/Kittorca.jpg',
  Kittorilla: baseImageUrl + 'Kittens/Kittorilla.jpg',
  Kitturtle: baseImageUrl + 'Kittens/Kitturtle.jpg',
  Kittybear: baseImageUrl + 'Kittens/Kittybear.jpg',
  'Kitty Blob': baseImageUrl + 'Kittens/Kitty%20Blob.jpg',
  Kittyling: baseImageUrl + 'Kittens/Kittyling.jpg',
  Kittypan: baseImageUrl + 'Kittens/Kittypan.jpg',
  Kittypenguin: baseImageUrl + 'Kittens/Kittypenguin.jpg',
  Kittyphant: baseImageUrl + 'Kittens/Kittyphant.jpg',
  'Kitty Pug': baseImageUrl + 'Kittens/Kitty%20Pug.jpg',
  'Kitty Rat': baseImageUrl + 'Kittens/Kitty%20Rat.jpg',
  Lelephant: baseImageUrl + 'Lion/Lelephant.jpg',
  Lion: baseImageUrl + 'Lion/Lion.jpg',
  Lionbear: baseImageUrl + 'Lion/Lionbear.jpg',
  'Lion Cub': baseImageUrl + 'Lion/Lion%20Cub.jpg',
  Lionda: baseImageUrl + 'Lion/Lionda.jpg',
  Lionelk: baseImageUrl + 'Lion/Lionelk.jpg',
  Lionfish: baseImageUrl + 'Lion/Lionfish.jpg',
  Lionfly: baseImageUrl + 'Lion/Lionfly.jpg',
  Lionguin: baseImageUrl + 'Lion/Lionguin.jpg',
  Lionilla: baseImageUrl + 'Lion/Lionilla.jpg',
  'Lion Kitty': baseImageUrl + 'Kittens/Lion%20Kitty.jpg',
  Lionling: baseImageUrl + 'Lion/Lionling.jpg',
  Lionorca: baseImageUrl + 'Lion/Lionorca.jpg',
  Lionpug: baseImageUrl + 'Lion/Lionpug.jpg',
  'Lion Rat': baseImageUrl + 'Lion/Lion%20Rat.jpg',
  Lionshark: baseImageUrl + 'Lion/Lionshark.jpg',
  Lionturtle: baseImageUrl + 'Lion/Lionturtle.jpg',
  Litten: baseImageUrl + 'Lion/Litten.jpg',
  'Naked Blobfish': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Blobfish.jpg',
  'Naked Butterfly': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Butterfly.jpg',
  'Naked Duckling': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Duckling.jpg',
  'Naked Elephant': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Elephant.jpg',
  'Naked Lion': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Lion.jpg',
  'Naked Mole Bear': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Mole%20Bear.jpg',
  'Naked Mole Elk': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Mole%20Elk.jpg',
  'Naked Mole Gorilla': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Mole%20Gorilla.jpg',
  'Naked Mole Kitten': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Mole%20Kitten.jpg',
  'Naked Mole Orca': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Mole%20Orca.jpg',
  'Naked Mole Pug': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Mole%20Pug.jpg',
  'Naked Mole Rat': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Mole%20Rat.jpg',
  'Naked Mole Shark': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Mole%20Shark.jpg',
  'Naked Panda': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Panda.jpg',
  'Naked Penguin': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Penguin.jpg',
  'Naked Rat Baby': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Rat%20Baby.jpg',
  'Naked Turtle': baseImageUrl + 'Naked%20Mole%20Rat/Naked%20Turtle.jpg',
  Orca: baseImageUrl + 'Orca/Orca.jpg',
  'Orca Bear': baseImageUrl + 'Orca/Orca%20Bear.jpg',
  Orcablob: baseImageUrl + 'Orca/Orcablob.jpg',
  Orcafly: baseImageUrl + 'Orca/Orcafly.jpg',
  Orcanda: baseImageUrl + 'Orca/Orcanda.jpg',
  Orcapeng: baseImageUrl + 'Orca/Orcapeng.jpg',
  Orcaphant: baseImageUrl + 'Orca/Orcaphant.jpg',
  Orcapug: baseImageUrl + 'Orca/Orcapug.jpg',
  Orcarat: baseImageUrl + 'Orca/Orcarat.jpg',
  Orcashark: baseImageUrl + 'Orca/Orcashark.jpg',
  Orcaturtle: baseImageUrl + 'Orca/Orcaturtle.jpg',
  Orcelk: baseImageUrl + 'Orca/Orcelk.jpg',
  Orcilla: baseImageUrl + 'Orca/Orcilla.jpg',
  Orcling: baseImageUrl + 'Orca/Orcling.jpg',
  Orclion: baseImageUrl + 'Orca/Orclion.jpg',
  Orkitten: baseImageUrl + 'Orca/Orkitten.jpg',
  Panda: baseImageUrl + 'Panda/Panda.jpg',
  Pandablob: baseImageUrl + 'Panda/Pandablob.jpg',
  Pandacat: baseImageUrl + 'Panda/Pandacat.jpg',
  'Panda Cub': baseImageUrl + 'Panda/Panda%20Cub.jpg',
  Pandafly: baseImageUrl + 'Panda/Pandafly.jpg',
  Pandaling: baseImageUrl + 'Panda/Pandaling.jpg',
  Pandalion: baseImageUrl + 'Panda/Pandalion.jpg',
  Pandalla: baseImageUrl + 'Panda/Pandalla.jpg',
  Pandaphant: baseImageUrl + 'Panda/Pandaphant.jpg',
  Pandapug: baseImageUrl + 'Panda/Pandapug.jpg',
  Pandarat: baseImageUrl + 'Panda/Pandarat.jpg',
  Pandashark: baseImageUrl + 'Panda/Pandashark.jpg',
  Pandaturtle: baseImageUrl + 'Panda/Pandaturtle.jpg',
  Pandelk: baseImageUrl + 'Panda/Pandelk.jpg',
  Pandorca: baseImageUrl + 'Panda/Pandorca.jpg',
  Panduin: baseImageUrl + 'Panda/Panduin.jpg',
  Pearda: baseImageUrl + 'Panda/Pearda.jpg',
  Pelephant: baseImageUrl + 'Penguin/Pelephant.jpg',
  Pelk: baseImageUrl + 'Pugs/Pelk.jpg',
  Penda: baseImageUrl + 'Penguin/Penda.jpg',
  Pengbear: baseImageUrl + 'Penguin/Pengbear.jpg',
  Penggerfly: baseImageUrl + 'Penguin/Penggerfly.jpg',
  Pengkitty: baseImageUrl + 'Penguin/Pengkitty.jpg',
  Pengling: baseImageUrl + 'Penguin/Pengling.jpg',
  Pengpug: baseImageUrl + 'Penguin/Pengpug.jpg',
  Penguelk: baseImageUrl + 'Penguin/Penguelk.jpg',
  Penguilion: baseImageUrl + 'Penguin/Penguilion.jpg',
  Penguilla: baseImageUrl + 'Penguin/Penguilla.jpg',
  Penguin: baseImageUrl + 'Penguin/Penguin.jpg',
  'Penguin Chick': baseImageUrl + 'Penguin/Penguin%20Chick.jpg',
  Penguinfish: baseImageUrl + 'Penguin/Penguinfish.jpg',
  Penguinrat: baseImageUrl + 'Penguin/Penguinrat.jpg',
  'Penguin Shark': baseImageUrl + 'Penguin/Penguin%20Shark.jpg',
  Penguorca: baseImageUrl + 'Penguin/Penguorca.jpg',
  Pengurtle: baseImageUrl + 'Penguin/Pengurtle.jpg',
  Plobfish: baseImageUrl + 'Pugs/Plobfish.jpg',
  Pug: baseImageUrl + 'Pugs/Pug.jpg',
  Pugbear: baseImageUrl + 'Pugs/Pugbear.jpg',
  Pugda: baseImageUrl + 'Pugs/Pugda.jpg',
  Puggerfly: baseImageUrl + 'Pugs/Puggerfly.jpg',
  Puggerphant: baseImageUrl + 'Pugs/Puggerphant.jpg',
  Pugguin: baseImageUrl + 'Pugs/Pugguin.jpg',
  Puggy: baseImageUrl + 'Pugs/Puggy.jpg',
  Pugitten: baseImageUrl + 'Pugs/Pugitten.jpg',
  Pugling: baseImageUrl + 'Pugs/Pugling.jpg',
  Puglion: baseImageUrl + 'Pugs/Puglion.jpg',
  Pugorca: baseImageUrl + 'Pugs/Pugorca.jpg',
  Pugorilla: baseImageUrl + 'Pugs/Pugorilla.jpg',
  Pugrat: baseImageUrl + 'Pugs/Pugrat.jpg',
  Pugshark: baseImageUrl + 'Pugs/Pugshark.jpg',
  Pugurtle: baseImageUrl + 'Pugs/Pugurtle.jpg',
  Shanguin: baseImageUrl + 'Shark/Shanguin.jpg',
  Shark: baseImageUrl + 'Shark/Shark.jpg',
  Sharkbear: baseImageUrl + 'Shark/Sharkbear.jpg',
  Sharkephant: baseImageUrl + 'Shark/Sharkephant.jpg',
  Sharkerfly: baseImageUrl + 'Shark/Sharkerfly.jpg',
  Sharkitten: baseImageUrl + 'Shark/Sharkitten.jpg',
  'Shark Kitty': baseImageUrl + 'Kittens/Shark%20Kitty.jpg',
  Sharkling: baseImageUrl + 'Shark/Sharkling.jpg',
  Sharkorilla: baseImageUrl + 'Shark/Sharkorilla.jpg',
  'Shark Rat': baseImageUrl + 'Shark/Shark%20Rat.jpg',
  Sharnda: baseImageUrl + 'Shark/Sharnda.jpg',
  Shelk: baseImageUrl + 'Shark/Shelk.jpg',
  Shlion: baseImageUrl + 'Shark/Shlion.jpg',
  Shlobfish: baseImageUrl + 'Shark/Shlobfish.jpg',
  Shorca: baseImageUrl + 'Shark/Shorca.jpg',
  Shug: baseImageUrl + 'Shark/Shug.jpg',
  Shurtle: baseImageUrl + 'Shark/Shurtle.jpg',
  'Tiny Turtle': baseImageUrl + 'Turtle/Tiny%20Turtle.jpg',
  Turkitten: baseImageUrl + 'Turtle/Turkitten.jpg',
  Turtanda: baseImageUrl + 'Turtle/Turtanda.jpg',
  Turtelephant: baseImageUrl + 'Turtle/Turtelephant.jpg',
  Turtelk: baseImageUrl + 'Turtle/Turtelk.jpg',
  Turtilla: baseImageUrl + 'Turtle/Turtilla.jpg',
  Turtle: baseImageUrl + 'Turtle/Turtle.jpg',
  'Turtle Bear': baseImageUrl + 'Turtle/Turtle%20Bear.jpg',
  Turtleblob: baseImageUrl + 'Turtle/Turtleblob.jpg',
  Turtlepeng: baseImageUrl + 'Turtle/Turtlepeng.jpg',
  Turtlerat: baseImageUrl + 'Turtle/Turtlerat.jpg',
  Turtleshark: baseImageUrl + 'Turtle/Turtleshark.jpg',
  Turtling: baseImageUrl + 'Turtle/Turtling.jpg',
  Turtlion: baseImageUrl + 'Turtle/Turtlion.jpg',
  Turtorca: baseImageUrl + 'Turtle/Turtorca.jpg',
  Turtpug: baseImageUrl + 'Turtle/Turtpug.jpg',
  Turtterfly: baseImageUrl + 'Turtle/Turtterfly.jpg',
}
