// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  TypedMap,
  Entity,
  Value,
  ValueKind,
  store,
  Address,
  Bytes,
  BigInt,
  BigDecimal
} from "@graphprotocol/graph-ts";

export class KeeperAddDrop extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save KeeperAddDrop entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save KeeperAddDrop entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("KeeperAddDrop", id.toString(), this);
  }

  static load(id: string): KeeperAddDrop | null {
    return store.get("KeeperAddDrop", id) as KeeperAddDrop | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get dropAddress(): string {
    let value = this.get("dropAddress");
    return value.toString();
  }

  set dropAddress(value: string) {
    this.set("dropAddress", Value.fromString(value));
  }

  get title(): string {
    let value = this.get("title");
    return value.toString();
  }

  set title(value: string) {
    this.set("title", Value.fromString(value));
  }

  get eggSupply(): BigInt {
    let value = this.get("eggSupply");
    return value.toBigInt();
  }

  set eggSupply(value: BigInt) {
    this.set("eggSupply", Value.fromBigInt(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }
}

export class KeeperBreed extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save KeeperBreed entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save KeeperBreed entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("KeeperBreed", id.toString(), this);
  }

  static load(id: string): KeeperBreed | null {
    return store.get("KeeperBreed", id) as KeeperBreed | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get from(): string {
    let value = this.get("from");
    return value.toString();
  }

  set from(value: string) {
    this.set("from", Value.fromString(value));
  }

  get parentA(): BigInt {
    let value = this.get("parentA");
    return value.toBigInt();
  }

  set parentA(value: BigInt) {
    this.set("parentA", Value.fromBigInt(value));
  }

  get parentB(): BigInt {
    let value = this.get("parentB");
    return value.toBigInt();
  }

  set parentB(value: BigInt) {
    this.set("parentB", Value.fromBigInt(value));
  }

  get eggId(): BigInt {
    let value = this.get("eggId");
    return value.toBigInt();
  }

  set eggId(value: BigInt) {
    this.set("eggId", Value.fromBigInt(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }
}

export class KeeperBurn extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save KeeperBurn entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save KeeperBurn entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("KeeperBurn", id.toString(), this);
  }

  static load(id: string): KeeperBurn | null {
    return store.get("KeeperBurn", id) as KeeperBurn | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get from(): string {
    let value = this.get("from");
    return value.toString();
  }

  set from(value: string) {
    this.set("from", Value.fromString(value));
  }

  get tokenId(): BigInt {
    let value = this.get("tokenId");
    return value.toBigInt();
  }

  set tokenId(value: BigInt) {
    this.set("tokenId", Value.fromBigInt(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }
}

export class KeeperBuyEgg extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save KeeperBuyEgg entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save KeeperBuyEgg entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("KeeperBuyEgg", id.toString(), this);
  }

  static load(id: string): KeeperBuyEgg | null {
    return store.get("KeeperBuyEgg", id) as KeeperBuyEgg | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get from(): string {
    let value = this.get("from");
    return value.toString();
  }

  set from(value: string) {
    this.set("from", Value.fromString(value));
  }

  get eggId(): BigInt {
    let value = this.get("eggId");
    return value.toBigInt();
  }

  set eggId(value: BigInt) {
    this.set("eggId", Value.fromBigInt(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }
}

export class KeeperHatch extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save KeeperHatch entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save KeeperHatch entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("KeeperHatch", id.toString(), this);
  }

  static load(id: string): KeeperHatch | null {
    return store.get("KeeperHatch", id) as KeeperHatch | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get from(): string {
    let value = this.get("from");
    return value.toString();
  }

  set from(value: string) {
    this.set("from", Value.fromString(value));
  }

  get eggId(): BigInt {
    let value = this.get("eggId");
    return value.toBigInt();
  }

  set eggId(value: BigInt) {
    this.set("eggId", Value.fromBigInt(value));
  }

  get tokenId(): BigInt {
    let value = this.get("tokenId");
    return value.toBigInt();
  }

  set tokenId(value: BigInt) {
    this.set("tokenId", Value.fromBigInt(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }
}

export class KeeperMint extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save KeeperMint entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save KeeperMint entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("KeeperMint", id.toString(), this);
  }

  static load(id: string): KeeperMint | null {
    return store.get("KeeperMint", id) as KeeperMint | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get from(): string {
    let value = this.get("from");
    return value.toString();
  }

  set from(value: string) {
    this.set("from", Value.fromString(value));
  }

  get tokenId(): BigInt {
    let value = this.get("tokenId");
    return value.toBigInt();
  }

  set tokenId(value: BigInt) {
    this.set("tokenId", Value.fromBigInt(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }
}

export class KeeperSwap extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save KeeperSwap entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save KeeperSwap entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("KeeperSwap", id.toString(), this);
  }

  static load(id: string): KeeperSwap | null {
    return store.get("KeeperSwap", id) as KeeperSwap | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get owner(): string {
    let value = this.get("owner");
    return value.toString();
  }

  set owner(value: string) {
    this.set("owner", Value.fromString(value));
  }

  get tokenId(): BigInt {
    let value = this.get("tokenId");
    return value.toBigInt();
  }

  set tokenId(value: BigInt) {
    this.set("tokenId", Value.fromBigInt(value));
  }

  get chainId(): BigInt {
    let value = this.get("chainId");
    return value.toBigInt();
  }

  set chainId(value: BigInt) {
    this.set("chainId", Value.fromBigInt(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }
}

export class Media extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Media entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Media entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Media", id.toString(), this);
  }

  static load(id: string): Media | null {
    return store.get("Media", id) as Media | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

  get owner(): string {
    let value = this.get("owner");
    return value.toString();
  }

  set owner(value: string) {
    this.set("owner", Value.fromString(value));
  }

  get creator(): string {
    let value = this.get("creator");
    return value.toString();
  }

  set creator(value: string) {
    this.set("creator", Value.fromString(value));
  }

  get prevOwner(): string {
    let value = this.get("prevOwner");
    return value.toString();
  }

  set prevOwner(value: string) {
    this.set("prevOwner", Value.fromString(value));
  }

  get approved(): string | null {
    let value = this.get("approved");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set approved(value: string | null) {
    if (value === null) {
      this.unset("approved");
    } else {
      this.set("approved", Value.fromString(value as string));
    }
  }

  get contentHash(): Bytes {
    let value = this.get("contentHash");
    return value.toBytes();
  }

  set contentHash(value: Bytes) {
    this.set("contentHash", Value.fromBytes(value));
  }

  get metadataHash(): Bytes {
    let value = this.get("metadataHash");
    return value.toBytes();
  }

  set metadataHash(value: Bytes) {
    this.set("metadataHash", Value.fromBytes(value));
  }

  get contentURI(): string {
    let value = this.get("contentURI");
    return value.toString();
  }

  set contentURI(value: string) {
    this.set("contentURI", Value.fromString(value));
  }

  get metadataURI(): string {
    let value = this.get("metadataURI");
    return value.toString();
  }

  set metadataURI(value: string) {
    this.set("metadataURI", Value.fromString(value));
  }

  get ownerBidShare(): BigInt {
    let value = this.get("ownerBidShare");
    return value.toBigInt();
  }

  set ownerBidShare(value: BigInt) {
    this.set("ownerBidShare", Value.fromBigInt(value));
  }

  get creatorBidShare(): BigInt {
    let value = this.get("creatorBidShare");
    return value.toBigInt();
  }

  set creatorBidShare(value: BigInt) {
    this.set("creatorBidShare", Value.fromBigInt(value));
  }

  get prevOwnerBidShare(): BigInt {
    let value = this.get("prevOwnerBidShare");
    return value.toBigInt();
  }

  set prevOwnerBidShare(value: BigInt) {
    this.set("prevOwnerBidShare", Value.fromBigInt(value));
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get createdAtBlockNumber(): BigInt {
    let value = this.get("createdAtBlockNumber");
    return value.toBigInt();
  }

  set createdAtBlockNumber(value: BigInt) {
    this.set("createdAtBlockNumber", Value.fromBigInt(value));
  }

  get burnedAtTimeStamp(): BigInt | null {
    let value = this.get("burnedAtTimeStamp");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set burnedAtTimeStamp(value: BigInt | null) {
    if (value === null) {
      this.unset("burnedAtTimeStamp");
    } else {
      this.set("burnedAtTimeStamp", Value.fromBigInt(value as BigInt));
    }
  }

  get burnedAtBlockNumber(): BigInt | null {
    let value = this.get("burnedAtBlockNumber");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set burnedAtBlockNumber(value: BigInt | null) {
    if (value === null) {
      this.unset("burnedAtBlockNumber");
    } else {
      this.set("burnedAtBlockNumber", Value.fromBigInt(value as BigInt));
    }
  }

  get currentAsk(): string | null {
    let value = this.get("currentAsk");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set currentAsk(value: string | null) {
    if (value === null) {
      this.unset("currentAsk");
    } else {
      this.set("currentAsk", Value.fromString(value as string));
    }
  }

  get currentBids(): Array<string> | null {
    let value = this.get("currentBids");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set currentBids(value: Array<string> | null) {
    if (value === null) {
      this.unset("currentBids");
    } else {
      this.set("currentBids", Value.fromStringArray(value as Array<string>));
    }
  }

  get inactiveAsks(): Array<string> | null {
    let value = this.get("inactiveAsks");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set inactiveAsks(value: Array<string> | null) {
    if (value === null) {
      this.unset("inactiveAsks");
    } else {
      this.set("inactiveAsks", Value.fromStringArray(value as Array<string>));
    }
  }

  get inactiveBids(): Array<string> | null {
    let value = this.get("inactiveBids");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set inactiveBids(value: Array<string> | null) {
    if (value === null) {
      this.unset("inactiveBids");
    } else {
      this.set("inactiveBids", Value.fromStringArray(value as Array<string>));
    }
  }

  get transfers(): Array<string> | null {
    let value = this.get("transfers");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set transfers(value: Array<string> | null) {
    if (value === null) {
      this.unset("transfers");
    } else {
      this.set("transfers", Value.fromStringArray(value as Array<string>));
    }
  }

  get reserveAuctions(): Array<string> | null {
    let value = this.get("reserveAuctions");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set reserveAuctions(value: Array<string> | null) {
    if (value === null) {
      this.unset("reserveAuctions");
    } else {
      this.set(
        "reserveAuctions",
        Value.fromStringArray(value as Array<string>)
      );
    }
  }

  get name(): string | null {
    let value = this.get("name");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set name(value: string | null) {
    if (value === null) {
      this.unset("name");
    } else {
      this.set("name", Value.fromString(value as string));
    }
  }
}

export class User extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save User entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save User entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("User", id.toString(), this);
  }

  static load(id: string): User | null {
    return store.get("User", id) as User | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get authorizedUsers(): Array<string> | null {
    let value = this.get("authorizedUsers");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set authorizedUsers(value: Array<string> | null) {
    if (value === null) {
      this.unset("authorizedUsers");
    } else {
      this.set(
        "authorizedUsers",
        Value.fromStringArray(value as Array<string>)
      );
    }
  }

  get collection(): Array<string> {
    let value = this.get("collection");
    return value.toStringArray();
  }

  set collection(value: Array<string>) {
    this.set("collection", Value.fromStringArray(value));
  }

  get creations(): Array<string> {
    let value = this.get("creations");
    return value.toStringArray();
  }

  set creations(value: Array<string>) {
    this.set("creations", Value.fromStringArray(value));
  }

  get currentBids(): Array<string> | null {
    let value = this.get("currentBids");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set currentBids(value: Array<string> | null) {
    if (value === null) {
      this.unset("currentBids");
    } else {
      this.set("currentBids", Value.fromStringArray(value as Array<string>));
    }
  }
}

export class Ask extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Ask entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Ask entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Ask", id.toString(), this);
  }

  static load(id: string): Ask | null {
    return store.get("Ask", id) as Ask | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get media(): string {
    let value = this.get("media");
    return value.toString();
  }

  set media(value: string) {
    this.set("media", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

  get currency(): string {
    let value = this.get("currency");
    return value.toString();
  }

  set currency(value: string) {
    this.set("currency", Value.fromString(value));
  }

  get amount(): BigInt {
    let value = this.get("amount");
    return value.toBigInt();
  }

  set amount(value: BigInt) {
    this.set("amount", Value.fromBigInt(value));
  }

  get owner(): string {
    let value = this.get("owner");
    return value.toString();
  }

  set owner(value: string) {
    this.set("owner", Value.fromString(value));
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get createdAtBlockNumber(): BigInt {
    let value = this.get("createdAtBlockNumber");
    return value.toBigInt();
  }

  set createdAtBlockNumber(value: BigInt) {
    this.set("createdAtBlockNumber", Value.fromBigInt(value));
  }

  get lazy(): boolean {
    let value = this.get("lazy");
    return value.toBoolean();
  }

  set lazy(value: boolean) {
    this.set("lazy", Value.fromBoolean(value));
  }

  get dropId(): BigInt {
    let value = this.get("dropId");
    return value.toBigInt();
  }

  set dropId(value: BigInt) {
    this.set("dropId", Value.fromBigInt(value));
  }

  get tokenTypeName(): string {
    let value = this.get("tokenTypeName");
    return value.toString();
  }

  set tokenTypeName(value: string) {
    this.set("tokenTypeName", Value.fromString(value));
  }
}

export class Bid extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Bid entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Bid entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Bid", id.toString(), this);
  }

  static load(id: string): Bid | null {
    return store.get("Bid", id) as Bid | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

  get media(): string {
    let value = this.get("media");
    return value.toString();
  }

  set media(value: string) {
    this.set("media", Value.fromString(value));
  }

  get currency(): string {
    let value = this.get("currency");
    return value.toString();
  }

  set currency(value: string) {
    this.set("currency", Value.fromString(value));
  }

  get amount(): BigInt {
    let value = this.get("amount");
    return value.toBigInt();
  }

  set amount(value: BigInt) {
    this.set("amount", Value.fromBigInt(value));
  }

  get sellOnShare(): BigInt {
    let value = this.get("sellOnShare");
    return value.toBigInt();
  }

  set sellOnShare(value: BigInt) {
    this.set("sellOnShare", Value.fromBigInt(value));
  }

  get bidder(): string {
    let value = this.get("bidder");
    return value.toString();
  }

  set bidder(value: string) {
    this.set("bidder", Value.fromString(value));
  }

  get recipient(): string {
    let value = this.get("recipient");
    return value.toString();
  }

  set recipient(value: string) {
    this.set("recipient", Value.fromString(value));
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get createdAtBlockNumber(): BigInt {
    let value = this.get("createdAtBlockNumber");
    return value.toBigInt();
  }

  set createdAtBlockNumber(value: BigInt) {
    this.set("createdAtBlockNumber", Value.fromBigInt(value));
  }

  get lazy(): boolean {
    let value = this.get("lazy");
    return value.toBoolean();
  }

  set lazy(value: boolean) {
    this.set("lazy", Value.fromBoolean(value));
  }

  get dropId(): BigInt {
    let value = this.get("dropId");
    return value.toBigInt();
  }

  set dropId(value: BigInt) {
    this.set("dropId", Value.fromBigInt(value));
  }

  get tokenTypeName(): string {
    let value = this.get("tokenTypeName");
    return value.toString();
  }

  set tokenTypeName(value: string) {
    this.set("tokenTypeName", Value.fromString(value));
  }
}

export class InactiveBid extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save InactiveBid entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save InactiveBid entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("InactiveBid", id.toString(), this);
  }

  static load(id: string): InactiveBid | null {
    return store.get("InactiveBid", id) as InactiveBid | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

  get media(): string {
    let value = this.get("media");
    return value.toString();
  }

  set media(value: string) {
    this.set("media", Value.fromString(value));
  }

  get type(): string {
    let value = this.get("type");
    return value.toString();
  }

  set type(value: string) {
    this.set("type", Value.fromString(value));
  }

  get currency(): string {
    let value = this.get("currency");
    return value.toString();
  }

  set currency(value: string) {
    this.set("currency", Value.fromString(value));
  }

  get amount(): BigInt {
    let value = this.get("amount");
    return value.toBigInt();
  }

  set amount(value: BigInt) {
    this.set("amount", Value.fromBigInt(value));
  }

  get sellOnShare(): BigInt {
    let value = this.get("sellOnShare");
    return value.toBigInt();
  }

  set sellOnShare(value: BigInt) {
    this.set("sellOnShare", Value.fromBigInt(value));
  }

  get bidder(): string {
    let value = this.get("bidder");
    return value.toString();
  }

  set bidder(value: string) {
    this.set("bidder", Value.fromString(value));
  }

  get recipient(): string {
    let value = this.get("recipient");
    return value.toString();
  }

  set recipient(value: string) {
    this.set("recipient", Value.fromString(value));
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get createdAtBlockNumber(): BigInt {
    let value = this.get("createdAtBlockNumber");
    return value.toBigInt();
  }

  set createdAtBlockNumber(value: BigInt) {
    this.set("createdAtBlockNumber", Value.fromBigInt(value));
  }

  get inactivatedAtTimestamp(): BigInt {
    let value = this.get("inactivatedAtTimestamp");
    return value.toBigInt();
  }

  set inactivatedAtTimestamp(value: BigInt) {
    this.set("inactivatedAtTimestamp", Value.fromBigInt(value));
  }

  get inactivatedAtBlockNumber(): BigInt {
    let value = this.get("inactivatedAtBlockNumber");
    return value.toBigInt();
  }

  set inactivatedAtBlockNumber(value: BigInt) {
    this.set("inactivatedAtBlockNumber", Value.fromBigInt(value));
  }

  get lazy(): boolean {
    let value = this.get("lazy");
    return value.toBoolean();
  }

  set lazy(value: boolean) {
    this.set("lazy", Value.fromBoolean(value));
  }

  get dropId(): BigInt {
    let value = this.get("dropId");
    return value.toBigInt();
  }

  set dropId(value: BigInt) {
    this.set("dropId", Value.fromBigInt(value));
  }

  get tokenTypeName(): string {
    let value = this.get("tokenTypeName");
    return value.toString();
  }

  set tokenTypeName(value: string) {
    this.set("tokenTypeName", Value.fromString(value));
  }
}

export class InactiveAsk extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save InactiveAsk entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save InactiveAsk entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("InactiveAsk", id.toString(), this);
  }

  static load(id: string): InactiveAsk | null {
    return store.get("InactiveAsk", id) as InactiveAsk | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

  get media(): string {
    let value = this.get("media");
    return value.toString();
  }

  set media(value: string) {
    this.set("media", Value.fromString(value));
  }

  get type(): string {
    let value = this.get("type");
    return value.toString();
  }

  set type(value: string) {
    this.set("type", Value.fromString(value));
  }

  get currency(): string {
    let value = this.get("currency");
    return value.toString();
  }

  set currency(value: string) {
    this.set("currency", Value.fromString(value));
  }

  get amount(): BigInt {
    let value = this.get("amount");
    return value.toBigInt();
  }

  set amount(value: BigInt) {
    this.set("amount", Value.fromBigInt(value));
  }

  get owner(): string {
    let value = this.get("owner");
    return value.toString();
  }

  set owner(value: string) {
    this.set("owner", Value.fromString(value));
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get createdAtBlockNumber(): BigInt {
    let value = this.get("createdAtBlockNumber");
    return value.toBigInt();
  }

  set createdAtBlockNumber(value: BigInt) {
    this.set("createdAtBlockNumber", Value.fromBigInt(value));
  }

  get inactivatedAtTimestamp(): BigInt {
    let value = this.get("inactivatedAtTimestamp");
    return value.toBigInt();
  }

  set inactivatedAtTimestamp(value: BigInt) {
    this.set("inactivatedAtTimestamp", Value.fromBigInt(value));
  }

  get inactivatedAtBlockNumber(): BigInt {
    let value = this.get("inactivatedAtBlockNumber");
    return value.toBigInt();
  }

  set inactivatedAtBlockNumber(value: BigInt) {
    this.set("inactivatedAtBlockNumber", Value.fromBigInt(value));
  }

  get lazy(): boolean {
    let value = this.get("lazy");
    return value.toBoolean();
  }

  set lazy(value: boolean) {
    this.set("lazy", Value.fromBoolean(value));
  }

  get dropId(): BigInt {
    let value = this.get("dropId");
    return value.toBigInt();
  }

  set dropId(value: BigInt) {
    this.set("dropId", Value.fromBigInt(value));
  }

  get tokenTypeName(): string {
    let value = this.get("tokenTypeName");
    return value.toString();
  }

  set tokenTypeName(value: string) {
    this.set("tokenTypeName", Value.fromString(value));
  }
}

export class Currency extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Currency entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Currency entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Currency", id.toString(), this);
  }

  static load(id: string): Currency | null {
    return store.get("Currency", id) as Currency | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get name(): string {
    let value = this.get("name");
    return value.toString();
  }

  set name(value: string) {
    this.set("name", Value.fromString(value));
  }

  get symbol(): string {
    let value = this.get("symbol");
    return value.toString();
  }

  set symbol(value: string) {
    this.set("symbol", Value.fromString(value));
  }

  get decimals(): i32 {
    let value = this.get("decimals");
    return value.toI32();
  }

  set decimals(value: i32) {
    this.set("decimals", Value.fromI32(value));
  }

  get liquidity(): BigInt {
    let value = this.get("liquidity");
    return value.toBigInt();
  }

  set liquidity(value: BigInt) {
    this.set("liquidity", Value.fromBigInt(value));
  }

  get activeBids(): Array<string> | null {
    let value = this.get("activeBids");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set activeBids(value: Array<string> | null) {
    if (value === null) {
      this.unset("activeBids");
    } else {
      this.set("activeBids", Value.fromStringArray(value as Array<string>));
    }
  }

  get activeAsks(): Array<string> | null {
    let value = this.get("activeAsks");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set activeAsks(value: Array<string> | null) {
    if (value === null) {
      this.unset("activeAsks");
    } else {
      this.set("activeAsks", Value.fromStringArray(value as Array<string>));
    }
  }

  get inactiveBids(): Array<string> | null {
    let value = this.get("inactiveBids");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set inactiveBids(value: Array<string> | null) {
    if (value === null) {
      this.unset("inactiveBids");
    } else {
      this.set("inactiveBids", Value.fromStringArray(value as Array<string>));
    }
  }

  get inactiveAsks(): Array<string> | null {
    let value = this.get("inactiveAsks");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set inactiveAsks(value: Array<string> | null) {
    if (value === null) {
      this.unset("inactiveAsks");
    } else {
      this.set("inactiveAsks", Value.fromStringArray(value as Array<string>));
    }
  }
}

export class Transfer extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Transfer entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Transfer entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Transfer", id.toString(), this);
  }

  static load(id: string): Transfer | null {
    return store.get("Transfer", id) as Transfer | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

  get media(): string {
    let value = this.get("media");
    return value.toString();
  }

  set media(value: string) {
    this.set("media", Value.fromString(value));
  }

  get from(): string {
    let value = this.get("from");
    return value.toString();
  }

  set from(value: string) {
    this.set("from", Value.fromString(value));
  }

  get to(): string {
    let value = this.get("to");
    return value.toString();
  }

  set to(value: string) {
    this.set("to", Value.fromString(value));
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get createdAtBlockNumber(): BigInt {
    let value = this.get("createdAtBlockNumber");
    return value.toBigInt();
  }

  set createdAtBlockNumber(value: BigInt) {
    this.set("createdAtBlockNumber", Value.fromBigInt(value));
  }
}

export class URIUpdate extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save URIUpdate entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save URIUpdate entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("URIUpdate", id.toString(), this);
  }

  static load(id: string): URIUpdate | null {
    return store.get("URIUpdate", id) as URIUpdate | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

  get type(): string {
    let value = this.get("type");
    return value.toString();
  }

  set type(value: string) {
    this.set("type", Value.fromString(value));
  }

  get from(): string {
    let value = this.get("from");
    return value.toString();
  }

  set from(value: string) {
    this.set("from", Value.fromString(value));
  }

  get to(): string {
    let value = this.get("to");
    return value.toString();
  }

  set to(value: string) {
    this.set("to", Value.fromString(value));
  }

  get media(): string {
    let value = this.get("media");
    return value.toString();
  }

  set media(value: string) {
    this.set("media", Value.fromString(value));
  }

  get owner(): string {
    let value = this.get("owner");
    return value.toString();
  }

  set owner(value: string) {
    this.set("owner", Value.fromString(value));
  }

  get updater(): string {
    let value = this.get("updater");
    return value.toString();
  }

  set updater(value: string) {
    this.set("updater", Value.fromString(value));
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get createdAtBlockNumber(): BigInt {
    let value = this.get("createdAtBlockNumber");
    return value.toBigInt();
  }

  set createdAtBlockNumber(value: BigInt) {
    this.set("createdAtBlockNumber", Value.fromBigInt(value));
  }
}

export class ReserveAuctionBid extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save ReserveAuctionBid entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save ReserveAuctionBid entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("ReserveAuctionBid", id.toString(), this);
  }

  static load(id: string): ReserveAuctionBid | null {
    return store.get("ReserveAuctionBid", id) as ReserveAuctionBid | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

  get reserveAuction(): string {
    let value = this.get("reserveAuction");
    return value.toString();
  }

  set reserveAuction(value: string) {
    this.set("reserveAuction", Value.fromString(value));
  }

  get amount(): BigInt {
    let value = this.get("amount");
    return value.toBigInt();
  }

  set amount(value: BigInt) {
    this.set("amount", Value.fromBigInt(value));
  }

  get bidder(): string {
    let value = this.get("bidder");
    return value.toString();
  }

  set bidder(value: string) {
    this.set("bidder", Value.fromString(value));
  }

  get bidType(): string {
    let value = this.get("bidType");
    return value.toString();
  }

  set bidType(value: string) {
    this.set("bidType", Value.fromString(value));
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get createdAtBlockNumber(): BigInt {
    let value = this.get("createdAtBlockNumber");
    return value.toBigInt();
  }

  set createdAtBlockNumber(value: BigInt) {
    this.set("createdAtBlockNumber", Value.fromBigInt(value));
  }
}

export class InactiveReserveAuctionBid extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(
      id !== null,
      "Cannot save InactiveReserveAuctionBid entity without an ID"
    );
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save InactiveReserveAuctionBid entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("InactiveReserveAuctionBid", id.toString(), this);
  }

  static load(id: string): InactiveReserveAuctionBid | null {
    return store.get(
      "InactiveReserveAuctionBid",
      id
    ) as InactiveReserveAuctionBid | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

  get reserveAuction(): string {
    let value = this.get("reserveAuction");
    return value.toString();
  }

  set reserveAuction(value: string) {
    this.set("reserveAuction", Value.fromString(value));
  }

  get amount(): BigInt {
    let value = this.get("amount");
    return value.toBigInt();
  }

  set amount(value: BigInt) {
    this.set("amount", Value.fromBigInt(value));
  }

  get bidder(): string {
    let value = this.get("bidder");
    return value.toString();
  }

  set bidder(value: string) {
    this.set("bidder", Value.fromString(value));
  }

  get bidType(): string {
    let value = this.get("bidType");
    return value.toString();
  }

  set bidType(value: string) {
    this.set("bidType", Value.fromString(value));
  }

  get bidInactivatedAtTimestamp(): BigInt {
    let value = this.get("bidInactivatedAtTimestamp");
    return value.toBigInt();
  }

  set bidInactivatedAtTimestamp(value: BigInt) {
    this.set("bidInactivatedAtTimestamp", Value.fromBigInt(value));
  }

  get bidInactivatedAtBlockNumber(): BigInt {
    let value = this.get("bidInactivatedAtBlockNumber");
    return value.toBigInt();
  }

  set bidInactivatedAtBlockNumber(value: BigInt) {
    this.set("bidInactivatedAtBlockNumber", Value.fromBigInt(value));
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get createdAtBlockNumber(): BigInt {
    let value = this.get("createdAtBlockNumber");
    return value.toBigInt();
  }

  set createdAtBlockNumber(value: BigInt) {
    this.set("createdAtBlockNumber", Value.fromBigInt(value));
  }
}

export class ReserveAuction extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save ReserveAuction entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save ReserveAuction entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("ReserveAuction", id.toString(), this);
  }

  static load(id: string): ReserveAuction | null {
    return store.get("ReserveAuction", id) as ReserveAuction | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }

  get tokenContract(): string {
    let value = this.get("tokenContract");
    return value.toString();
  }

  set tokenContract(value: string) {
    this.set("tokenContract", Value.fromString(value));
  }

  get tokenId(): BigInt {
    let value = this.get("tokenId");
    return value.toBigInt();
  }

  set tokenId(value: BigInt) {
    this.set("tokenId", Value.fromBigInt(value));
  }

  get token(): string {
    let value = this.get("token");
    return value.toString();
  }

  set token(value: string) {
    this.set("token", Value.fromString(value));
  }

  get media(): string | null {
    let value = this.get("media");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set media(value: string | null) {
    if (value === null) {
      this.unset("media");
    } else {
      this.set("media", Value.fromString(value as string));
    }
  }

  get approved(): boolean {
    let value = this.get("approved");
    return value.toBoolean();
  }

  set approved(value: boolean) {
    this.set("approved", Value.fromBoolean(value));
  }

  get duration(): BigInt {
    let value = this.get("duration");
    return value.toBigInt();
  }

  set duration(value: BigInt) {
    this.set("duration", Value.fromBigInt(value));
  }

  get expectedEndTimestamp(): BigInt | null {
    let value = this.get("expectedEndTimestamp");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set expectedEndTimestamp(value: BigInt | null) {
    if (value === null) {
      this.unset("expectedEndTimestamp");
    } else {
      this.set("expectedEndTimestamp", Value.fromBigInt(value as BigInt));
    }
  }

  get firstBidTime(): BigInt | null {
    let value = this.get("firstBidTime");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set firstBidTime(value: BigInt | null) {
    if (value === null) {
      this.unset("firstBidTime");
    } else {
      this.set("firstBidTime", Value.fromBigInt(value as BigInt));
    }
  }

  get reservePrice(): BigInt {
    let value = this.get("reservePrice");
    return value.toBigInt();
  }

  set reservePrice(value: BigInt) {
    this.set("reservePrice", Value.fromBigInt(value));
  }

  get curatorFeePercentage(): i32 {
    let value = this.get("curatorFeePercentage");
    return value.toI32();
  }

  set curatorFeePercentage(value: i32) {
    this.set("curatorFeePercentage", Value.fromI32(value));
  }

  get tokenOwner(): string {
    let value = this.get("tokenOwner");
    return value.toString();
  }

  set tokenOwner(value: string) {
    this.set("tokenOwner", Value.fromString(value));
  }

  get curator(): string {
    let value = this.get("curator");
    return value.toString();
  }

  set curator(value: string) {
    this.set("curator", Value.fromString(value));
  }

  get auctionCurrency(): string {
    let value = this.get("auctionCurrency");
    return value.toString();
  }

  set auctionCurrency(value: string) {
    this.set("auctionCurrency", Value.fromString(value));
  }

  get status(): string {
    let value = this.get("status");
    return value.toString();
  }

  set status(value: string) {
    this.set("status", Value.fromString(value));
  }

  get currentBid(): string | null {
    let value = this.get("currentBid");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set currentBid(value: string | null) {
    if (value === null) {
      this.unset("currentBid");
    } else {
      this.set("currentBid", Value.fromString(value as string));
    }
  }

  get previousBids(): Array<string> | null {
    let value = this.get("previousBids");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set previousBids(value: Array<string> | null) {
    if (value === null) {
      this.unset("previousBids");
    } else {
      this.set("previousBids", Value.fromStringArray(value as Array<string>));
    }
  }

  get approvedTimestamp(): BigInt | null {
    let value = this.get("approvedTimestamp");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set approvedTimestamp(value: BigInt | null) {
    if (value === null) {
      this.unset("approvedTimestamp");
    } else {
      this.set("approvedTimestamp", Value.fromBigInt(value as BigInt));
    }
  }

  get approvedBlockNumber(): BigInt | null {
    let value = this.get("approvedBlockNumber");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set approvedBlockNumber(value: BigInt | null) {
    if (value === null) {
      this.unset("approvedBlockNumber");
    } else {
      this.set("approvedBlockNumber", Value.fromBigInt(value as BigInt));
    }
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get createdAtBlockNumber(): BigInt {
    let value = this.get("createdAtBlockNumber");
    return value.toBigInt();
  }

  set createdAtBlockNumber(value: BigInt) {
    this.set("createdAtBlockNumber", Value.fromBigInt(value));
  }

  get finalizedAtTimestamp(): BigInt | null {
    let value = this.get("finalizedAtTimestamp");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set finalizedAtTimestamp(value: BigInt | null) {
    if (value === null) {
      this.unset("finalizedAtTimestamp");
    } else {
      this.set("finalizedAtTimestamp", Value.fromBigInt(value as BigInt));
    }
  }

  get finalizedAtBlockNumber(): BigInt | null {
    let value = this.get("finalizedAtBlockNumber");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set finalizedAtBlockNumber(value: BigInt | null) {
    if (value === null) {
      this.unset("finalizedAtBlockNumber");
    } else {
      this.set("finalizedAtBlockNumber", Value.fromBigInt(value as BigInt));
    }
  }
}

export class TokenType extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save TokenType entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save TokenType entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("TokenType", id.toString(), this);
  }

  static load(id: string): TokenType | null {
    return store.get("TokenType", id) as TokenType | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get kind(): string {
    let value = this.get("kind");
    return value.toString();
  }

  set kind(value: string) {
    this.set("kind", Value.fromString(value));
  }

  get supply(): BigInt {
    let value = this.get("supply");
    return value.toBigInt();
  }

  set supply(value: BigInt) {
    this.set("supply", Value.fromBigInt(value));
  }

  get contentHash(): Bytes {
    let value = this.get("contentHash");
    return value.toBytes();
  }

  set contentHash(value: Bytes) {
    this.set("contentHash", Value.fromBytes(value));
  }

  get metadataHash(): Bytes {
    let value = this.get("metadataHash");
    return value.toBytes();
  }

  set metadataHash(value: Bytes) {
    this.set("metadataHash", Value.fromBytes(value));
  }

  get contentURI(): string {
    let value = this.get("contentURI");
    return value.toString();
  }

  set contentURI(value: string) {
    this.set("contentURI", Value.fromString(value));
  }

  get metadataURI(): string {
    let value = this.get("metadataURI");
    return value.toString();
  }

  set metadataURI(value: string) {
    this.set("metadataURI", Value.fromString(value));
  }

  get ownerBidShare(): BigInt {
    let value = this.get("ownerBidShare");
    return value.toBigInt();
  }

  set ownerBidShare(value: BigInt) {
    this.set("ownerBidShare", Value.fromBigInt(value));
  }

  get creatorBidShare(): BigInt {
    let value = this.get("creatorBidShare");
    return value.toBigInt();
  }

  set creatorBidShare(value: BigInt) {
    this.set("creatorBidShare", Value.fromBigInt(value));
  }

  get prevOwnerBidShare(): BigInt {
    let value = this.get("prevOwnerBidShare");
    return value.toBigInt();
  }

  set prevOwnerBidShare(value: BigInt) {
    this.set("prevOwnerBidShare", Value.fromBigInt(value));
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get transactionHash(): string {
    let value = this.get("transactionHash");
    return value.toString();
  }

  set transactionHash(value: string) {
    this.set("transactionHash", Value.fromString(value));
  }
}
