// deploy/04_deploy_zoo_keeper.ts
import { HardhatRuntimeEnvironment } from 'hardhat/types'
import { DeployFunction } from 'hardhat-deploy/types'
import { getDeployerAddress } from '../lib/deploy_helper'

const func: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployments, ethers, getNamedAccounts } = hre
  const { deploy } = deployments
  const { deployer } = await getNamedAccounts()

  const useProxy = !hre.network.live

  const marketAddress = (await deployments.get('ZooMarket')).address
  const mediaAddress = (await deployments.get('ZooMedia')).address
  const tokenAddress = (await deployments.get('ZooToken')).address

  const deployment = await deploy('ZooKeeper', {
    from: deployer,
    args: [marketAddress, mediaAddress, tokenAddress],
    log: true,
  })

  const keeper = await hre.ethers.getContractAt('ZooKeeper', deployment.address);

  // Add first drop
  // const [dropID, dropAddress] = await keeper.callStatic.addDrop('Gen 0', 16000, 210);
  const [id, address] = await keeper.addDrop('Gen 0', 16000, 210)
  console.log('ZooDrop', id, address);

  await keeper.setTokenURI(id, "basicEgg", "basicEgg.tokenURI1");
  await keeper.setMetadataURI(id, "basicEgg", "basicEgg.metadataURI1");
  await keeper.setTokenURI(id, "hybridEgg", "hybridEgg.tokenURI1");
  await keeper.setMetadataURI(id, "hybridEgg", "hybridEgg.metadataURI1");

  await keeper.addAnimal(id, "Pug", 100, "Common", 5500, "test","test");
  await keeper.addAnimal(id, "Butterfly", 100, "Common", 5500, "test1","test1");
  await keeper.addAnimal(id, "Kitten", 100, "Common", 5500, "test2","test2");
  await keeper.addAnimal(id, "Turtle", 100, "Common", 5500, "test3","test3");

  await keeper.addAnimal(id, "Penguin", 100, "Common", 5500, "test4","test4");
  await keeper.addAnimal(id, "Duckling", 100, "Common", 5500, "test5","test5");
  await keeper.addAnimal(id, "Orca", 100, "Common", 5500, "test6","test6");
  await keeper.addAnimal(id, "Elk", 100, "Common", 5500, "test7","test7");

  await keeper.addAnimal(id, "Panda", 100, "Common", 5500, "test8","test8");
  await keeper.addAnimal(id, "Gorilla", 100, "Common", 5500, "test9","test9");
  await keeper.addAnimal(id, "Lion", 100, "Common", 5500, "test11","test11");
  await keeper.addAnimal(id, "Elephant", 100, "Common", 5500,"test12","test12");

  await keeper.addAnimal(id, "Bear", 100, "Common", 5500, "test13","test13");
  await keeper.addAnimal(id, "Shark", 100, "Common", 5500, "test14","test14");

  await keeper.addAnimal(id, "Blobfish", 100, "Common", 5500, "test15","test15");
  await keeper.addAnimal(id, "Naked Mole Rat", 100, "Common", 5500, "test16","test16");

  await keeper.addHybrid(id, "Baby Elephant", "Elephant", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Baby%20Elephant.jpg", "testElephant")
  await keeper.addHybrid(id, "Baby Elk", "Elk", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Baby%20Elk.jpg", "testElk")
  await keeper.addHybrid(id, "Baby Gorilla", "Gorilla", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Baby%20Gorilla.jpg", "testGorilla")
  await keeper.addHybrid(id, "Baby Orca", "Orca", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Baby%20Orca.jpg", "testOrca")
  await keeper.addHybrid(id, "Baby Shark", "Shark", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Baby%20Shark.jpg", "testShark")
  await keeper.addHybrid(id, "Banda", "Bear", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Banda.jpg", "testBear")
  await keeper.addHybrid(id, "Bearblob", "Bear", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Bearblob.jpg", "testBear")
  await keeper.addHybrid(id, "Bearca", "Bear", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Bearca.jpg", "testBear")
  await keeper.addHybrid(id, "Bear Cub", "Bear", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Bear%20Cub.jpg", "testBear")
  await keeper.addHybrid(id, "Bearilla", "Bear", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Bearilla.jpg", "testBear")
  await keeper.addHybrid(id, "Bearling", "Bear", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Bearling.jpg", "testBear")
  await keeper.addHybrid(id, "Bearlion", "Bear", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Bearlion.jpg", "testBear")
  await keeper.addHybrid(id, "Bearpug", "Bear", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Bearpug.jpg", "testBear")
  await keeper.addHybrid(id, "Bearrat", "Bear", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Bearrat.jpg", "testBear")
  await keeper.addHybrid(id, "Bearshark", "Bear", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Bearshark.jpg", "testBear")
  await keeper.addHybrid(id, "Beartle", "Bear", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Beartle.jpg", "testBear")
  await keeper.addHybrid(id, "Beartten", "Bear", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Beartten.jpg", "testBear")
  await keeper.addHybrid(id, "Beartterfly", "Bear", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Beartterfly.jpg", "testBear")
  await keeper.addHybrid(id, "Belephant", "Bear", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Belephant.jpg", "testBear")
  await keeper.addHybrid(id, "Belk", "Bear", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Belk.jpg", "testBear")
  await keeper.addHybrid(id, "Benguin", "Bear", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Bear/Benguin.jpg", "testBear")
  await keeper.addHybrid(id, "Butterbear", "Butterfly", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterbear.jpg", "testButterfly")
  await keeper.addHybrid(id, "Butterblob", "Butterfly", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterblob.jpg", "testButterfly")
  await keeper.addHybrid(id, "Butterflanda", "Butterfly", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterflanda.jpg", "testButterfly")
  await keeper.addHybrid(id, "Butterflelk", "Butterfly", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterflelk.jpg", "testButterfly")
  await keeper.addHybrid(id, "Butterflenguin", "Butterfly", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterflenguin.jpg", "testButterfly")
  await keeper.addHybrid(id, "Butterfling", "Butterfly", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterfling.jpg", "testButterfly")
  await keeper.addHybrid(id, "Butterflion", "Butterfly", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterflion.jpg", "testButterfly")
  await keeper.addHybrid(id, "Butterflitten", "Butterfly", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterflitten.jpg", "testButterfly")
  await keeper.addHybrid(id, "Butterla", "Butterfly", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterla.jpg", "testButterfly")
  await keeper.addHybrid(id, "Butterphant", "Butterfly", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterphant.jpg", "testButterfly")
  await keeper.addHybrid(id, "Butterpug", "Butterfly", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterpug.jpg", "testButterfly")
  await keeper.addHybrid(id, "Butterrat", "Butterfly", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterrat.jpg", "testButterfly")
  await keeper.addHybrid(id, "Buttershark", "Butterfly", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Buttershark.jpg", "testButterfly")
  await keeper.addHybrid(id, "Buttorca", "Butterfly", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Buttorca.jpg", "testButterfly")
  await keeper.addHybrid(id, "Butturtle", "Butterfly", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butturtle.jpg", "testButterfly")
  await keeper.addHybrid(id, "Caterpillar", "Butterfly", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Caterpillar.jpg", "testButterfly")
  await keeper.addHybrid(id, "Dorca", "Duckling", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Dorca.jpg", "testDuckling")
  await keeper.addHybrid(id, "Duckbear", "Duckling", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Duckbear.jpg", "testDuckling")
  await keeper.addHybrid(id, "Duckblob", "Duckling", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Duckblob.jpg", "testDuckling")
  await keeper.addHybrid(id, "Duckda", "Duckling", "Pands", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Duckda.jpg", "testDuckling")
  await keeper.addHybrid(id, "Duckelk", "Duckling", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Duckelk.jpg", "testDuckling")
  await keeper.addHybrid(id, "Duckerfly", "Duckling", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Duckerfly.jpg", "testDuckling")
  await keeper.addHybrid(id, "Duckitten", "Duckling", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Duckitten.jpg", "testDuckling")
  await keeper.addHybrid(id, "Ducklephant", "Duckling", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Ducklephant.jpg", "testDuckling")
  await keeper.addHybrid(id, "Ducklinguin", "Duckling", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Ducklinguin.jpg", "testDuckling")
  await keeper.addHybrid(id, "Ducklion", "Duckling", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Ducklion.jpg", "testDuckling")
  await keeper.addHybrid(id, "Duckorilla", "Duckling", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Duckorilla.jpg", "testDuckling")
  await keeper.addHybrid(id, "DuckPug", "Duckling", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/DuckPug.jpg", "testDuckling")
  await keeper.addHybrid(id, "Duckrat", "Duckling", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Duckrat.jpg", "testDuckling")
  await keeper.addHybrid(id, "Duckshark", "Duckling", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Duckshark.jpg", "testDuckling")
  await keeper.addHybrid(id, "Durtle", "Duckling", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Duckling/Durtle.jpg", "testDuckling")
  await keeper.addHybrid(id, "Elebear", "Elephant", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elebear.jpg", "testElephant")
  await keeper.addHybrid(id, "Eleblob", "Elephant", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Eleblob.jpg", "testElephant")
  await keeper.addHybrid(id, "Elepanda", "Elephant", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elepanda.jpg", "testElephant")
  await keeper.addHybrid(id, "Elepenguin", "Elephant", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elepenguin.jpg", "testElephant")
  await keeper.addHybrid(id, "Elephantilla", "Elephant", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elephantilla.jpg", "testElephant")
  await keeper.addHybrid(id, "Elephantterfly", "Elephant", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elephantterfly.jpg", "testElephant")
  await keeper.addHybrid(id, "Elephanturtle", "Elephant", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elephanturtle.jpg", "testElephant")
  await keeper.addHybrid(id, "Elephelk", "Elephant", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elephelk.jpg", "testElephant")
  await keeper.addHybrid(id, "Elephitten", "Elephant", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elephitten.jpg", "testElephant")
  await keeper.addHybrid(id, "Elephling", "Elephant", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elephling.jpg", "testElephant")
  await keeper.addHybrid(id, "Elephlion", "Elephant", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elephlion.jpg", "testElephant")
  await keeper.addHybrid(id, "Elephorca", "Elephant", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elephorca.jpg", "testElephant")
  await keeper.addHybrid(id, "Elephrat", "Elephant", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elephrat.jpg", "testElephant")
  await keeper.addHybrid(id, "Elepug", "Elephant", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elepug.jpg", "testElephant")
  await keeper.addHybrid(id, "Eleshark", "Elephant", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Eleshark.jpg", "testElephant")
  await keeper.addHybrid(id, "Elka", "Elk", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elka.jpg", "testElk")
  await keeper.addHybrid(id, "Elkanda", "Elk", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkanda.jpg", "testElk")
  await keeper.addHybrid(id, "Elkbear", "Elk", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkbear.jpg", "testElk")
  await keeper.addHybrid(id, "Elkenguin", "Elk", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkenguin.jpg", "testElk")
  await keeper.addHybrid(id, "Elkephant", "Elk", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkephant.jpg", "testElk")
  await keeper.addHybrid(id, "Elkerfly", "Elk", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkerfly.jpg", "testElk")
  await keeper.addHybrid(id, "Elkfish", "Elk", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkfish.jpg", "testElk")
  await keeper.addHybrid(id, "Elkion", "Elk", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkion.jpg", "testElk")
  await keeper.addHybrid(id, "Elkitten", "Elk", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkitten.jpg", "testElk")
  await keeper.addHybrid(id, "Elkling", "Elk", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkling.jpg", "testElk")
  await keeper.addHybrid(id, "Elkorilla", "Elk", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkorilla.jpg", "testElk")
  await keeper.addHybrid(id, "Elkpug", "Elk", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkpug.jpg", "testElk")
  await keeper.addHybrid(id, "Elk Rat", "Elk", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elk%20Rat.jpg", "testElk")
  await keeper.addHybrid(id, "Elkshark", "Elk", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkshark.jpg", "testElk")
  await keeper.addHybrid(id, "Elkurtle", "Elk", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elk/Elkurtle.jpg", "testElk")
  await keeper.addHybrid(id, "Goranda", "Gorilla", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Goranda.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorca", "Gorilla", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorca.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorillabear", "Gorilla", "Near", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorillabear.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorillablob", "Gorilla", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorillablob.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorillafly", "Gorilla", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorillafly.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorillaguin", "Gorilla", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorillaguin.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorillaphant", "Gorilla", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorillaphant.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorilla Rat", "Gorilla", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorilla%20Rat.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorillark", "Gorilla", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorillark.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorillelk", "Gorilla", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorillelk.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorilling", "Gorilla", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorilling.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorillion", "Gorilla", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorillion.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorkitten", "Gorilla", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorkitten.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gorturtle", "Gorilla", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gorturtle.jpg", "testGorilla")
  await keeper.addHybrid(id, "Gug", "Gorilla", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Gug.jpg", "testGorilla")
  await keeper.addHybrid(id, "Kittelk", "Kitten", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kittelk.jpg", "testKitten")
  await keeper.addHybrid(id, "Kitten", "Kitten", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kitten.jpg", "testKitten")
  await keeper.addHybrid(id, "Kitterfly", "Kitten", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kitterfly.jpg", "testKitten")
  await keeper.addHybrid(id, "Kittorca", "Kitten", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kittorca.jpg", "testKitten")
  await keeper.addHybrid(id, "Kittorilla", "Kitten", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kittorilla.jpg", "testKitten")
  await keeper.addHybrid(id, "Kitturtle", "Kitten", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kitturtle.jpg", "testKitten")
  await keeper.addHybrid(id, "Kittybear", "Kitten", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kittybear.jpg", "testKitten")
  await keeper.addHybrid(id, "Kitty Blob", "Kitten", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kitty%20Blob.jpg", "testKitten")
  await keeper.addHybrid(id, "Kittyling", "Kitten", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kittyling.jpg", "testKitten")
  await keeper.addHybrid(id, "Kittypan", "Kitten", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kittypan.jpg", "testKitten")
  await keeper.addHybrid(id, "Kittypenguin", "Kitten", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kittypenguin.jpg", "testKitten")
  await keeper.addHybrid(id, "Kittyphant", "Kitten", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kittyphant.jpg", "testKitten")
  await keeper.addHybrid(id, "Kitty Pug", "Kitten", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kitty%20Pug.jpg", "testKitten")
  await keeper.addHybrid(id, "Kitty Rat", "Kitten", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Kitty%20Rat.jpg", "testKitten")
  await keeper.addHybrid(id, "Lelephant", "Lion", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lelephant.jpg", "testLion")
  await keeper.addHybrid(id, "Lionbear", "Lion", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lionbear.jpg", "testLion")
  await keeper.addHybrid(id, "Lion Cub", "Lion", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lion%20Cub.jpg", "testLion")
  await keeper.addHybrid(id, "Lionda", "Lion", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lionda.jpg", "testLion")
  await keeper.addHybrid(id, "Lionelk", "Lion", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lionelk.jpg", "testLion")
  await keeper.addHybrid(id, "Lionfish", "Lion", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lionfish.jpg", "testLion")
  await keeper.addHybrid(id, "Lionfly", "Lion", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lionfly.jpg", "testLion")
  await keeper.addHybrid(id, "Lionguin", "Lion", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lionguin.jpg", "testLion")
  await keeper.addHybrid(id, "Lionilla", "Lion", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lionilla.jpg", "testLion")
  await keeper.addHybrid(id, "Lion Kitty", "Kitten", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Lion%20Kitty.jpg", "testKitten")
  await keeper.addHybrid(id, "Lionling", "Lion", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lionling.jpg", "testLion")
  await keeper.addHybrid(id, "Lionorca", "Lion", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lionorca.jpg", "testLion")
  await keeper.addHybrid(id, "Lionpug", "Lion", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lionpug.jpg", "testLion")
  await keeper.addHybrid(id, "Lion Rat", "Lion", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lion%20Rat.jpg", "testLion")
  await keeper.addHybrid(id, "Lionshark", "Lion", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lionshark.jpg", "testLion")
  await keeper.addHybrid(id, "Lionturtle", "Lion", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Lionturtle.jpg", "testLion")
  await keeper.addHybrid(id, "Litten", "Lion", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Lion/Litten.jpg", "testLion")
  await keeper.addHybrid(id, "Naked Blobfish", "Naked Mole Rat", "Bloblfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Blobfish.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Butterfly", "Naked Mole Rat", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Butterfly.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Duckling", "Naked Mole Rat", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Duckling.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Elephant", "Naked Mole Rat", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Elephant.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Lion", "Naked Mole Rat", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Lion.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Mole Bear", "Naked Mole Rat", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Mole%20Bear.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Mole Elk", "Naked Mole Rat", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Mole%20Elk.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Mole Gorilla", "Naked Mole Rat", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Mole%20Gorilla.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Mole Kitten", "Naked Mole Rat", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Mole%20Kitten.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Mole Orca", "Naked Mole Rat", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Mole%20Orca.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Mole Pug", "Naked Mole Rat", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Mole%20Pug.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Mole Rat", "Naked Mole Rat", "Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Mole%20Rat.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Mole Shark", "Naked Mole Rat", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Mole%20Shark.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Panda", "Naked Mole Rat", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Panda.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Penguin", "Naked Mole Rat", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Penguin.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Rat Baby", "Naked Mole Rat", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Rat%20Baby.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Naked Turtle", "Naked Mole Rat", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Naked%20Mole%20Rat/Naked%20Turtle.jpg", "testNaked Mole Rat")
  await keeper.addHybrid(id, "Orca Bear", "Orca", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orca%20Bear.jpg", "testOrca")
  await keeper.addHybrid(id, "Orcablob", "Orca", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orcablob.jpg", "testOrca")
  await keeper.addHybrid(id, "Orcafly", "Orca", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orcafly.jpg", "testOrca")
  await keeper.addHybrid(id, "Orcanda", "Orca", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orcanda.jpg", "testOrca")
  await keeper.addHybrid(id, "Orcapeng", "Orca", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orcapeng.jpg", "testOrca")
  await keeper.addHybrid(id, "Orcaphant", "Orca", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orcaphant.jpg", "testOrca")
  await keeper.addHybrid(id, "Orcapug", "Orca", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orcapug.jpg", "testOrca")
  await keeper.addHybrid(id, "Orcarat", "Orca", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orcarat.jpg", "testOrca")
  await keeper.addHybrid(id, "Orcashark", "Orca", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orcashark.jpg", "testOrca")
  await keeper.addHybrid(id, "Orcaturtle", "Orca", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orcaturtle.jpg", "testOrca")
  await keeper.addHybrid(id, "Orcelk", "Orca", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orcelk.jpg", "testOrca")
  await keeper.addHybrid(id, "Orcilla", "Orca", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orcilla.jpg", "testOrca")
  await keeper.addHybrid(id, "Orcling", "Orca", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orcling.jpg", "testOrca")
  await keeper.addHybrid(id, "Orclion", "Orca", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orclion.jpg", "testOrca")
  await keeper.addHybrid(id, "Orkitten", "Orca", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Orca/Orkitten.jpg", "testOrca")
  await keeper.addHybrid(id, "Pandablob", "Panda", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandablob.jpg", "testPanda")
  await keeper.addHybrid(id, "Pandacat", "Panda", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandacat.jpg", "testPanda")
  await keeper.addHybrid(id, "Panda Cub", "Panda", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Panda%20Cub.jpg", "testPanda")
  await keeper.addHybrid(id, "Pandafly", "Panda", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandafly.jpg", "testPanda")
  await keeper.addHybrid(id, "Pandaling", "Panda", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandaling.jpg", "testPanda")
  await keeper.addHybrid(id, "Pandalion", "Panda", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandalion.jpg", "testPanda")
  await keeper.addHybrid(id, "Pandalla", "Panda", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandalla.jpg", "testPanda")
  await keeper.addHybrid(id, "Pandaphant", "Panda", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandaphant.jpg", "testPanda")
  await keeper.addHybrid(id, "Pandapug", "Panda", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandapug.jpg", "testPanda")
  await keeper.addHybrid(id, "Pandarat", "Panda", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandarat.jpg", "testPanda")
  await keeper.addHybrid(id, "Pandashark", "Panda", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandashark.jpg", "testPanda")
  await keeper.addHybrid(id, "Pandaturtle", "Panda", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandaturtle.jpg", "testPanda")
  await keeper.addHybrid(id, "Pandelk", "Panda", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandelk.jpg", "testPanda")
  await keeper.addHybrid(id, "Pandorca", "Panda", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pandorca.jpg", "testPanda")
  await keeper.addHybrid(id, "Panduin", "Panda", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Panduin.jpg", "testPanda")
  await keeper.addHybrid(id, "Pearda", "Panda", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Pearda.jpg", "testPanda")
  await keeper.addHybrid(id, "Pelephant", "Penguin", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Pelephant.jpg", "testPenguin")
  await keeper.addHybrid(id, "Pelk", "Pug", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Pelk.jpg", "testPug")
  await keeper.addHybrid(id, "Penda", "Penguin", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Penda.jpg", "testPenguin")
  await keeper.addHybrid(id, "Pengbear", "Penguin", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Pengbear.jpg", "testPenguin")
  await keeper.addHybrid(id, "Penggerfly", "Penguin", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Penggerfly.jpg", "testPenguin")
  await keeper.addHybrid(id, "Pengkitty", "Penguin", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Pengkitty.jpg", "testPenguin")
  await keeper.addHybrid(id, "Pengling", "Penguin", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Pengling.jpg", "testPenguin")
  await keeper.addHybrid(id, "Pengpug", "Penguin", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Pengpug.jpg", "testPenguin")
  await keeper.addHybrid(id, "Penguelk", "Penguin", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Penguelk.jpg", "testPenguin")
  await keeper.addHybrid(id, "Penguilion", "Penguin", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Penguilion.jpg", "testPenguin")
  await keeper.addHybrid(id, "Penguilla", "Penguin", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Penguilla.jpg", "testPenguin")
  await keeper.addHybrid(id, "Penguin Chick", "Penguin", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Penguin%20Chick.jpg", "testPenguin")
  await keeper.addHybrid(id, "Penguinfish", "Penguin", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Penguinfish.jpg", "testPenguin")
  await keeper.addHybrid(id, "Penguinrat", "Penguin", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Penguinrat.jpg", "testPenguin")
  await keeper.addHybrid(id, "Penguin Shark", "Penguin", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Penguin%20Shark.jpg", "testPenguin")
  await keeper.addHybrid(id, "Penguorca", "Penguin", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Penguorca.jpg", "testPenguin")
  await keeper.addHybrid(id, "Pengurtle", "Penguin", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Penguin/Pengurtle.jpg", "testPenguin")
  await keeper.addHybrid(id, "Plobfish", "Pug", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Plobfish.jpg", "testPug")
  await keeper.addHybrid(id, "Pugbear", "Pug", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Pugbear.jpg", "testPug")
  await keeper.addHybrid(id, "Pugda", "Pug", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Pugda.jpg", "testPug")
  await keeper.addHybrid(id, "Puggerfly", "Pug", "Buttefly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Puggerfly.jpg", "testPug")
  await keeper.addHybrid(id, "Puggerphant", "Pug", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Puggerphant.jpg", "testPug")
  await keeper.addHybrid(id, "Pugguin", "Pug", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Pugguin.jpg", "testPug")
  await keeper.addHybrid(id, "Puggy", "Pug", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Puggy.jpg", "testPug")
  await keeper.addHybrid(id, "Pugitten", "Pug", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Pugitten.jpg", "testPug")
  await keeper.addHybrid(id, "Pugling", "Pug", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Pugling.jpg", "testPug")
  await keeper.addHybrid(id, "Puglion", "Pug", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Puglion.jpg", "testPug")
  await keeper.addHybrid(id, "Pugorca", "Pug", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Pugorca.jpg", "testPug")
  await keeper.addHybrid(id, "Pugorilla", "Pug", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Pugorilla.jpg", "testPug")
  await keeper.addHybrid(id, "Pugrat", "Pug", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Pugrat.jpg", "testPug")
  await keeper.addHybrid(id, "Pugshark", "Pug", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Pugshark.jpg", "testPug")
  await keeper.addHybrid(id, "Pugurtle", "Pug", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Pug/Pugurtle.jpg", "testPug")
  await keeper.addHybrid(id, "Shanguin", "Shark", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Shanguin.jpg", "testShark")
  await keeper.addHybrid(id, "Sharkbear", "Shark", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Sharkbear.jpg", "testShark")
  await keeper.addHybrid(id, "Sharkephant", "Shark", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Sharkephant.jpg", "testShark")
  await keeper.addHybrid(id, "Sharkerfly", "Shark", "Buttefly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Sharkerfly.jpg", "testShark")
  await keeper.addHybrid(id, "Sharkitten", "Shark", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Sharkitten.jpg", "testShark")
  await keeper.addHybrid(id, "Shark Kitty", "Kitten", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Kitten/Shark%20Kitty.jpg", "testKitten")
  await keeper.addHybrid(id, "Sharkling", "Shark", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Sharkling.jpg", "testShark")
  await keeper.addHybrid(id, "Sharkorilla", "Shark", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Sharkorilla.jpg", "testShark")
  await keeper.addHybrid(id, "Shark Rat", "Shark", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Shark%20Rat.jpg", "testShark")
  await keeper.addHybrid(id, "Sharnda", "Shark", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Sharnda.jpg", "testShark")
  await keeper.addHybrid(id, "Shelk", "Shark", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Shelk.jpg", "testShark")
  await keeper.addHybrid(id, "Shlion", "Shark", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Shlion.jpg", "testShark")
  await keeper.addHybrid(id, "Shlobfish", "Shark", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Shlobfish.jpg", "testShark")
  await keeper.addHybrid(id, "Shorca", "Shark", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Shorca.jpg", "testShark")
  await keeper.addHybrid(id, "Shug", "Shark", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Shug.jpg", "testShark")
  await keeper.addHybrid(id, "Shurtle", "Shark", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Shurtle.jpg", "testShark")
  await keeper.addHybrid(id, "Turtpug", "Turtle", "Pug", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtpug.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtterfly", "Turtle", "Butterfly", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtterfly.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turkitten", "Turtle", "Kitten", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turkitten.jpg", "testTurtle")
  await keeper.addHybrid(id, "Tiny Turtle", "Turtle", "Turtle", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Tiny%20Turtle.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtlepeng", "Turtle", "Penguin", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtlepeng.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtling", "Turtle", "Duckling", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtling.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtorca", "Turtle", "Orca", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtorca.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtelk", "Turtle", "Elk", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtelk.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtanda", "Turtle", "Panda", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtanda.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtilla", "Turtle", "Gorilla", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtilla.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtelephant", "Turtle", "Elephant", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtelephant.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtlion", "Turtle", "Lion", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtlion.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtle Bear", "Turtle", "Bear", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtle%20Bear.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtleshark", "Turtle", "Shark", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtleshark.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtleblob", "Turtle", "Blobfish", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtleblob.jpg", "testTurtle")
  await keeper.addHybrid(id, "Turtlerat", "Turtle", "Naked Mole Rat", 100, "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Turtlerat.jpg", "testTurtle")

  return !useProxy // When live network, record the script as executed to prevent rexecution
}

export default func
func.id = 'deploy_zoo_keeper' // ID required to prevent reexecution
func.tags = ['ZooKeeper']
