/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Hybrid } from "../Hybrid";

export class Hybrid__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): Hybrid {
    return new Contract(address, _abi, signerOrProvider) as Hybrid;
  }
}

const _abi = [
  {
    inputs: [],
    name: "data",
    outputs: [
      {
        internalType: "string",
        name: "assetURI",
        type: "string",
      },
      {
        internalType: "string",
        name: "assetGatewayURL",
        type: "string",
      },
      {
        internalType: "string",
        name: "metadataURI",
        type: "string",
      },
      {
        internalType: "string",
        name: "metadataGatewayURL",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "description",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "parent1",
    outputs: [
      {
        internalType: "contract Animal",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "parent2",
    outputs: [
      {
        internalType: "contract Animal",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
