export const animalMapping = {
  1: {
    animalId: "1",
    name: "Panda Cub",
    description: "Mystery",
    yield: "543",
    boost: "5678",
    rarity: "Legendary",
    dob: "1627064176",
    imageUrl:
    "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Panda/Panda%20Cub.jpg",
    startBid: "500",
    currentBid: "500",
    buyNow: "1000",
    listed: true,
    bloodline: "pure"
  },
  2: {
     animalId: "2",
     name: "Baby Gorilla",
     description: "LOL",
     yield: "4223",
     boost: "2",
     rarity: "Rare",
     dob: "1627064176",
     imageUrl: "http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Gorilla/Baby%20Gorilla.jpg",
     startBid: "400",
     currentBid: "800",
     buyNow: "900",
     listed: true,
     bloodline: "pure"

  },
  3: {
     animalId: "3",
     name: "Baby Turtle",
     description: "WOOF wO0F",
     yield: "321",
     boost: "2",
     rarity: "Uncommon",
     dob: "1627064176",
     imageUrl:
        "https://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Turtle/Tiny%20Turtle.jpg",
     startBid: "300",
     currentBid: "500",
     buyNow: "600",
     listed: true,
     bloodline: "pure"
  },
  4: {
     animalId: "4",
     name: "Baby Shark",
     description: "BARK",
     yield: "31",
     boost: "22",
     rarity: "Common",
     dob: "1627064176",
     imageUrl:
        "https://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Shark/Baby%20Shark.jpg",
     startBid: "200",
     currentBid: "201",
     buyNow: "300",
     listed: false,
     bloodline: "pure"
  },
  10: {
     animalId: "10",
     name: "Butterrat",
     description: "Meow",
     yield: "23",
     boost: "2200",
     rarity: "Legendary",
     dob: "1627064176",
     imageUrl: "https://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Butterfly/Butterrat.jpg",
     startBid: "200",
     currentBid: "201",
     buyNow: "300",
     listed: false,
     bloodline: "hybrid"
  },
  11: {
     animalId: "11",
     name: "Pandafly",
     description: "",
     yield: "23",
     boost: "2200",
     rarity: "Legendary",
     dob: "1627064176",
     imageUrl: `${window.location.origin}/static/images/Pandafly.jpg`,
     startBid: "200",
     currentBid: "201",
     buyNow: "300",
     listed: false,
     bloodline: "hybrid"
  },
  12: {
    animalId: "11",
     name: "Elepenguin",
     description: "",
     yield: "23",
     boost: "2200",
     rarity: "Legendary",
     dob: "1627064176",
     imageUrl: `http://res.cloudinary.com/htcif1pyx/image/upload/w_600/v1/CryptoZoo/9:16%20Aspect%20Ratio/Elephant/Elepenguin.jpg`,
     startBid: "200",
     currentBid: "201",
     buyNow: "300",
     listed: false,
     bloodline: "hybrid"
  }
}